### ISSUE TITLE
Rework the url preview form so that it submits via http GET so you can bookmark the result

### ISSUE THREAD

**Issue by brendanheywood** [Catalyst-QUT-2023/moodle#5]
At the moment we are using the moodle formslib to make the preview submit form. This is good for most cases but it was a couple downsides:
1) it is always a http post (without doing more work)
2) it is optimised for long forms with many fields, not for a simple single field form like this

So I'd like to see the form rebuild manually so that it submits via get and results in a url with the preview url in the url so you can deep link and bookmark these pages.

This means:

- [x] removing the formslib form
- [x] making a manual form using another mustache template
- [x] grabbing the data out of the url using optional_param directly instead of formslib doing this for you

This also paves the way for optimizing the display of this form in #6

**Comment by gaetgoler** [comment]
I reworked this changes on 5-rework-the-url-preview-form-so-that...2 branch.
Here is the changes: 
1. Removed the formslib form
2. Made a manual form using simple mustache template
3. The new url-preview now grabs the data using param instead of formslib
If there is no further changes needed, I will merge this branch into existing our dev branch
